spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auction-service
            uri: http://localhost:8096
              - Path=/v1/auction/**
          - id: user-service
            uri: http://localhost:8095
              - Path=/v1/security/**