spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: task-service
            uri:
              http://localhost:8096
            predicates:
              - Path=/v1/auction/**

          - id: user-service
            uri:
              http://localhost:8095
            predicates:
              - Path=/v1/security/**