spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/liquibase-changelog.yaml
  kafka:
    bootstrap-servers: localhost:29092
  application:
    name: auction-service
  datasource:
    url: jdbc:postgresql://localhost:5433/auction-service
    username: ${POSTGRES_PASSWORD}
    password: ${POSTGRES_USER}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 8096

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  endpoints.web.exposure.include: 'prometheus, health'
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true



